import { Customer } from './customer';

export const CUSTOMERS: Customer[] = [
  {
    nfmAccountId: '49280266',
    accountId: 2,
    partyId: 816,
    partyTypeId: 1,
    partyTypeName: 'Person',
    firstName: 'TODD',
    middleName: '',
    lastName: 'VAN GALEN',
    dateOfBirth: '1990-01-01T00:00:00',
    occupationName: '',
    address_id: null,
    employerName: '',
    addressLineOneText: '4624 MAVERICK WAY',
    addressLineTwoText: '',
    addressCityName: 'CARROLLTON',
    addressStateProvinceCode: 'TX',
    addressPostalPlusFourCode: '75010-4411',
    addressCountryCode: 'USA',
    phoneWork: null,
    phoneHome: "18609,2145572721",
    partyEmail: '1,todd.vangalen@freemanco.com',
    errorMsg: null,
  },
  {
    nfmAccountId: '27079748',
    accountId: 7,
    partyId: 488,
    partyTypeId: 1,
    partyTypeName: 'Person',
    firstName: 'MARIA',
    middleName: 'test',
    lastName: 'VACHAPITTACK',
    dateOfBirth: '1990-01-01T00:00:00',
    occupationName: 'RESIDENT PHYSICIAN',
    employerName: 'NEBRASKA MEDICINE',
    address_id: 7,
    addressLineOneText: '10545 SHIRLEY ST',
    addressLineTwoText: '',
    addressCityName: 'OMAHA',
    addressStateProvinceCode: 'NE',
    addressPostalPlusFourCode: '68124-1059',
    addressCountryCode: 'USA',
    phoneWork: "68091, 4025523999",
    phoneHome: "18614,4057620714",
    partyEmail: '3,mariarv@okstate.edu|4,mvachapittack@gmail.comi',
    errorMsg: null,
  },
  {
    nfmAccountId: '27079748',
    accountId: 7,
    partyId: 49611,
    partyTypeId: 1,
    partyTypeName: 'Person',
    firstName: 'MARIA',
    middleName: 'test',
    lastName: 'VACHAPITTACK',
    dateOfBirth: '1990-01-01T00:00:00',
    occupationName: 'GRAD TEACHING ASST',
    employerName: 'OSU',
    address_id: null,
    addressLineOneText: null,
    addressLineTwoText: null,
    addressCityName: null,
    addressStateProvinceCode: null,
    addressPostalPlusFourCode: null,
    addressCountryCode: null,
    phoneWork: '1212341234',
    phoneHome: '1212341234',
    partyEmail: '1,todd.vangalen@freemanco.com',
    errorMsg: null,
  },
];
